FROM python:3
ENV PYTHONUNBUFFERED=1
RUN mkdir /code
WORKDIR /code
COPY requirements-basic-django.txt /code/
RUN pip install -r requirements-basic-django.txt && \
	pip install mysql-python
COPY . /code/
